
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms'; // For ngModel
import { PostService } from '../../services/post.service';
import { Post } from '../../models/post.model'; 

@Component({
  selector: 'app-post-create',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule
  ],
  templateUrl: './post-create.component.html',
  styleUrls: ['./post-create.component.css']
})
export class PostCreateComponent implements OnInit {
  // Initialize a new Post object with default values
  // ID will be generated by the backend
  // createdAt and updatedAt will be generated by the backend
  newPost: Post = {
    id: 0, // Placeholder, backend will generate actual ID
    title: '',
    content: '',
    author: '',
    category: '',
    tags: '',
    published: false, // Default to not published
    createdAt: '', // Placeholder, backend will generate
    updatedAt: ''  // Placeholder, backend will generate
  };

  isLoading: boolean = false; // Indicates if a submission is in progress
  errorMessage: string | null = null;
  successMessage: string | null = null;

  constructor(
    private postService: PostService,
    private router: Router
  ) { }

  ngOnInit(): void {
    // No data fetching needed for creation form on init
  }

  /**
   * Handles the form submission to create a new post.
   */
  onSubmit(): void {
    this.isLoading = true;
    this.errorMessage = null;
    this.successMessage = null;

    // Call the service to create the post
    this.postService.createPost(this.newPost).subscribe({
      next: (createdPost) => {
        this.successMessage = 'Post created successfully!';
        this.isLoading = false;
        console.log('New Post created:', createdPost);

        // Optional: Reset the form or navigate
        this.newPost = {
          id: 0, title: '', content: '', author: '', category: '',
          tags: '', published: false, createdAt: '', updatedAt: ''
        }; // Reset form
        setTimeout(() => {
          this.router.navigate(['/']); // Navigate back to the posts list after 2 seconds
        }, 2000);
      },
      error: (error) => {
        console.error('Error creating post:', error);
        this.errorMessage = 'Failed to create post. Please try again.';
        this.isLoading = false;
      }
    });
  }

  /**
   * Navigates back to the main posts list without saving.
   */
  goBack(): void {
    this.router.navigate(['/admin']);
  }
}
