# portfolio/Dockerfile
# Stage 1: Build the Angular application
FROM node:18-alpine as build

WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .


# So, you should adjust the COPY command in Stage 2.
RUN npm run build --configuration=production 

# Stage 2: Create a minimal image just to hold the build output
FROM alpine:latest

WORKDIR /usr/share/nginx/html 

COPY --from=build /app/dist/portfolio/browser .

